reanahub/reana

- docs/requirements.txt
* Adds `docs/requirements.txt` so that ReadTheDocs can install all the
prerequisites for building the autodoc parts of the documentation.
> docs: ReadTheDocs configuration

- .gitignore
- scripts/reana
* add cli command to run reana-demo-helloworld example easily
`reana run helloworld`
Signed-off-by: Harri Hirvonsalo <harri.hirvonsalo@cern.ch>
> cli: add demo functionality to Reana cli script

- scripts/reana
* add support to run workflows from public github repositories
WIP
* Parsing of reana.yaml is not implemented properly / rigorously. It is just to demonstrate how reana specification could be used. Probably won't be beneficial to spend time on implementing yaml parsing in as shellcode, since there have been plans to move to python-based cli-script.
* Lot of duplicate code in run() and helloworld() functions. Will be cleaned before merging.
Signed-off-by: Harri Hirvonsalo <harri.hirvonsalo@cern.ch>
> cli: add support to run workflows from public github repositories [WIP]

- .gitignore
- scripts/reana
* Fixes "reana run" command with GitHub repository parameter.
* Adds forgotten verbose conditional printing for some details.
* Adds configuration-manifests to Git ignore file list.
> scripts: fix "run" command for GitHub repositories

- docs/examples.rst
* Amends few places where the old name "IPython notebook" was used.
> docs: IPython -> Jupyter notebook

- docs/components.rst
* Unifies release note links to point to GitHub where the release notes are
presented in a readable manner for all components. (closes #50)
> docs: unification of release note links

- docs/conf.py
- docs/developerguide.rst
- reana/cli.py
- setup.py
- tests/test_cli.py
* Initial release of ``reana`` helper script that facilitates working with
multiple repositories for local development and integration testing purposes.
> cli: initial release of ``reana`` helper script

- reana/cli.py
- tests/test_cli.py
* Filters away some components that are not dockerisable (such as
`reana-cluster`) when attempting to execute docker commands
(such as `reana docker-build`).
* Adds tests for select_components() as well.
> cli: filter components in docker commands

- reana/cli.py
- tests/test_cli.py
* Adds more options on how to specify component names for the `reana` helper
script. Accepts now also the canonical short names (`r-j-controller`) and the
current working directory based name (`.`).
* Enriches `reana` helper script documentation to cover all CLI options.
* Adds new example repository `reana-demo-cms-h4l`.
> cli: richer component name specification options

- reana/cli.py
- tests/test_cli.py
* Adds two new convenient helper commands to set up the shell environment and to
run selected REANA examples with selected workflow engines. Useful for local
integration testing purposes.
> cli: new setup-environment and run-example commands

- reana/cli.py
* Includes commit SHA1 and commit subject in the git-status output.
> cli: richer git-status

- reana/cli.py
* Amends ``run-example`` instructions how to upload code and data following up
the new convention in REANA demo examples.
(see reanahub/reana-demo-worldpopulation#23)
> cli: run-example code and data upload

- reana/cli.py
* Adds new command for easier deletion of pods. Closes #100
> cli: easy deletion of pods

- reana/cli.py
- tests/test_cli.py
Adds default output files in run-example function.
(Closes 98)
Signed-off-by: Jan Okraska <jan.okraska@cern.ch>
> cli: configurable outputs for run-example

- reana/cli.py
* Introduces `-s` option to `git-status` command in order to show the git short
status overview for components.
> cli: reana-dev git-status -s

- reana/cli.py
* New command `git-log` showing information about commits.
> cli: reana-dev git-log

- reana/cli.py
* Amends `subprocess.run()` call for Python-2.7 compatibility. (closes #116)
> cli: Python-2.7 compatibility fix

- docs/developerguide.rst
- reana/cli.py
* Introduces `reana-dev docker-build -b arg1=val1 -b arg2=val2` build argument
option in order to facilitate building images with arguments. Useful notably
for `-b DEBUG=true`. Amends documentation accordingly.
> cli: docker build arguments

- docs/developerguide.rst
- reana/cli.py
* Adds `docker-build -t latest` to the usage examples following the switch of
the defaults to build auto-generated tags instead of "latest".
> docs: docker-build -t latest

- reana/cli.py
* Adding flag that allows to run docker image build process in
background.
> cli: adding flag to build image in background

- Makefile
* In order to test bigger Docker images such as CMSSW, it is useful to allow
Minikube to have bigger RAM and disk size.
> make: configurable CPU, RAM, and disk size for minikube

- docs/userguide.rst
* Since the introduction of Jupyter Notebooks the necessity of accessing
files by non-root users became evident, now we add all non-root REANA
users to root group so we can access files and directories
(closes #149).
> docs: supporting non-root users

- Makefile
- reana/cli.py
* Adds new option to `reana-dev run-example` so all examples are tested
(closes #150).
* `make ci` runs all examples (closes #147).
> make: include all example when running CI

- reana/cli.py
* Removes forgotten `cwl-default-worker` as well. (addresses #169)
> cli: removal of cwl-default-worker

- reana/cli.py
* Uploads all declared inputs in ``reana.yaml`` file instead of
using hard-coded ``code``, ``data`` and ``inputs`` directories.
Necessary for e.g. ALICE examples.
> cli: run-example upload fix

- reana/cli.py
- reana/version.py
* Makes ``reana-dev version`` command help message consistent with newly
introduced ``reana-client version`` and ``reana-cluster version``.
> cli: version command help message

- AUTHORS.rst
- reana/cli.py
* Adds new CMS dimuon mass spectrum analysis example.
(addresses #202)
Signed-off-by: Ronald Dobos <ronald.dobos0@gmail.com>
> cli: new CMS dimuon mass spectrum example

- Makefile
* Kubernetes 1.16 comes with a few deprecations which will need
to be addressed before upgrading, see
more here https://github.com/reanahub/reana/issues/205.
> make: pin Kubernetes version to 1.15.4

- Makefile
* Eval doesn't fail if the command inside fails, it always returns
0 exit. If someone runs steps such as prefetch or build, the
step of connecting to Minikube's Docker daemon will fail silently
and the Docker client will connect to the local Docker daemon (if
it exists) or fail if there is no Docker daemon to connect to.
> make: fail if cannot connect to Minikube

- docs/userguide.rst
> docs: adds krb5s example

- Makefile
- reana/cli.py
Useful when having the GitLab integration set up i.e. the Ingress controller only accepts requests from a given host.
Usage example:
```zsh
$ SERVER_URL=https://cachopo.cern.ch DEMO=reana-demo-helloworld make example
```
Related to https://github.com/reanahub/reana-cluster/pull/241
Closes reanahub/reana-server#176
> make: add flag to set custom server url

- Makefile
* Catch appropriate REANA-Server message when the admin account is
created that would work for both PROD and DEV deployment scenarios.
> make: deployment detection improvement

- reana/cli.py
* Renames reana.io to www.reana.io, following up the repository name
change on GitHub.
> cli: www.reana.io

- Makefile
* Because of reanahub/reana-server#193, where we want to silence
start-up logs on R-Server we are losing DB events logs in prod
like setup. Now we need should check for REANA to be ready to
either Flask or uWSGI to be ready.
> make: check for Flask|uWSGI to be initialised

- reana/cli.py
* The ``docker-push`` command now accepts ``-t auto`` flag, like
``docker-build``.
> cli: docker-push accepting -t auto

- .gitignore
- MANIFEST.in
- Makefile
- docs/administratorguide.rst
- docs/developerguide.rst
- docs/gettingstarted.rst
- helm/reana/.helmignore
- helm/reana/Chart.lock
- helm/reana/Chart.yaml
- helm/reana/templates/NOTES.txt
- helm/reana/templates/cephfs.yaml
- helm/reana/templates/ingress.yaml
- helm/reana/templates/kerberos-config.yaml
- helm/reana/templates/postgres.yaml
- helm/reana/templates/reana-message-broker.yaml
- helm/reana/templates/reana-server.yaml
- helm/reana/templates/reana-ui.yaml
- helm/reana/templates/reana-workflow-controller.yaml
- helm/reana/templates/redis.yaml
- helm/reana/templates/roles.yaml
- helm/reana/templates/secrets.yaml
- helm/reana/templates/serviceaccount.yaml
- helm/reana/templates/wdb.yaml
- helm/reana/values.yaml
- reana/cli.py
- reana/k8s_utils.py
* Creates a new directory with the REANA Helm chart, helm/reana-stable
(closes #28):
```
$ helm install reana helm/reana
```
* Secrets stop being requested interactively, if not provided they will
be filled with default hardcoded values.
* Adds Traefik as a managed dependency, paves the way to do similar
with Postgres, Redis and RabbitMQ.
* Prefixes all REANA components with `reana-`.
> global: move cluster from reana-cluster to reana

- Makefile
closes #236
**Note:** When working on `reana-[commons|db]` component make sure to run `reana-dev git-submodule --update` after making some changes as a way to live reload, this way the affected component will get the changes on `modules/`. Thus rebuilding the image is not needed anymore.
> make: stop deleting modules folder

- .travis.yml
- Makefile
- helm/reana/Chart.yaml
- helm/reana/templates/NOTES.txt
- helm/reana/templates/reana-server.yaml
- helm/reana/templates/reana-workflow-controller.yaml
- helm/reana/templates/secrets.yaml
- helm/reana/values.yaml
- reana/cli.py
* Use `reana-dev` as Chart name since it is a development one.
* Hides error when `reana-dev` chart is not installed and we try to
uninstall.
* Adds environment variables from GitLab integration and CERN SSO
on dev mode, they were missing.
* Changes installation message.
> helm: cleanup

- Makefile
- helm/reana/Chart.lock
* Removes unnecessary sleep times in ``ci`` target after migration to helm.
* Updates traefik helm chart version.
> make: ci target speed-up

- reana/cli.py
* Fixes REANA cluster component pod names that got "reana-" prefix after
moving to Helm, making ``kubectl-delete-pod`` command to work again.
> make: cluster component pod name fix

- reana/cli.py
- tests/test_cli.py
* Does not use dots in workflow names anymore as per the new restart
workflow feature that does not allow workflow names with dots.
> cli: run-example workflow name fix

- reana/cli.py
- reana/version.py
- tests/test_cli.py
* Verifies presence of certain log messages that should be printed when
running `logs` command on demo examples.  Useful to test whether the
`logs` command returns what it should, as it happens in the past that
the command was broken. (see reanahub/reana-job-controller#232)
> cli: verify output of logs command during CI run

- Makefile
* VM setup is hardcoded to `minikube`, but if you use a different
profile, the configuration either fails (if there is no VM called
`minikube`) or it configures the wrong VM. It is important to note
that the created VBox VM's are named after the minikube context.
> make: fix VM configuration in setup

- reana/cli.py
> cli: fix for `kubectl-delete-pod -c r-ui` command

- reana/cli.py
- tests/test_cli.py
* Adds new `python-unit-tests` command that allows to launch all the
Python unit tests for desired components using independent virtual
environments for each REANA component. (Takes about ten minutes.)
(closes #282)
> cli: new `python-unit-tests` command

- MANIFEST.in
- benchmark/locustfile.py
- helm/reana/templates/reana-server.yaml
- helm/reana/templates/uwsgi-config.yaml
- helm/reana/values.yaml
- reana/cli.py
- reana/k8s_utils.py
closes reanahub/reana-server#228
Many performance tests were done using the new [`metrics-server`](https://kubernetes.io/docs/tasks/debug-application-cluster/resource-metrics-pipeline/)
```console
$ kubectl top pod reana-server-xyx
NAME.                CPU(cores)         MEMORY(bytes)   
reana-server-xyz.    0m                 312Mi
$ kubectl get --raw /apis/metrics.k8s.io/v1beta1/namespaces/default/pods/reana-server-xyz  | jq
{
"kind": "PodMetrics",
"apiVersion": "metrics.k8s.io/v1beta1",
"metadata": {
"name": "reana-server-xyz",
"namespace": "default",
"selfLink": "/apis/metrics.k8s.io/v1beta1/namespaces/default/pods/reana-server-xtz",
"creationTimestamp": "2020-04-13T14:58:14Z"
},
"timestamp": "2020-04-13T14:58:00Z",
"window": "1m0s",
"containers": [
{
"name": "rest-api",
"usage": { …
```
> helm: load uwsgi config as configmap

- .github/workflows/helm-releaser.yaml
- MANIFEST.in
- Makefile
- helm/configurations/values-dev.yaml
- helm/reana/Chart.yaml
- helm/reana/values.yaml
- scripts/update_images.sh
Closes https://github.com/reanahub/reana/issues/288
---
This PR includes automatic Helm Chart releases with [Helm Chart Releaser Action](https://github.com/marketplace/actions/helm-chart-releaser?version=v1.0.0-rc.2), leaving the following actions to be taken:
> helm: chart directory to reflect latest release

- reana/cli.py
- reana/k8s_utils.py
- setup.py
* This allows to setup-environment for multiple local REANA
instances and fixes the problem of always using `default` as
instance name (#292).
> cli: remove namespace from setup-environment

- Makefile
It was resulting in e.g. `helm install reana helm/reana  -fhelm/configurations/values-dev.yaml --wait`. Notice the lack of space between `-f` and its value.
> make: fix spacing typo

- .travis.yml
- helm/reana/README.md
- helm/reana/templates/reana-server.yaml
- helm/reana/templates/secrets.yaml
- helm/reana/values.yaml
- setup.py
closes reanahub/reana-db#66
⚠️ The [`reana-dev setup-environment` problem](https://github.com/reanahub/reana/blob/master/reana/cli.py#L1528-L1530) (encrypted token output) still need to be addressed or ticketized.
> helm: add reana secret key 

- Makefile
- helm/configurations/values-dev.yaml
- helm/reana/README.md
- helm/reana/templates/NOTES.txt
- helm/reana/templates/cronjobs.yaml
- helm/reana/templates/reana-mail.yaml
- helm/reana/templates/reana-server.yaml
- helm/reana/templates/secrets.yaml
- helm/reana/values.yaml
- reana/cli.py
- scripts/create-admin-user.sh
* Useful to program system wide status reports with cronjobs
(closes #308).
> helm: add optional notifications

- .github/workflows/helm-releaser.yaml
So we can control helm chart releaser github action workflows better and avoid extra runs.
> helm: trigger cr action on change Chart.yaml

- helm/reana/Chart.yaml
- helm/reana/templates/reana-workflow-controller.yaml
Fixes interactive sessions as workflow-controller calls
[`get_owner_access_token()`](https://github.com/reanahub/reana-workflow-controller/blob/master/reana_workflow_controller/workflow_run_manager.py#L258) that needs the `SECRET_KEY` to get the
access_token.
closes #325
> helm: add reana secret key env var

- helm/reana/templates/announcement-config.yaml
- helm/reana/templates/reana-server.yaml
closes reanahub/reana-ui#83
How to update the announcement:
```console
$ kubectl edit configmaps announcement-config
$ kubectl delete pod reana-server-xxx-yyy
> helm: add announcement configmap

- CHANGES.rst
- Makefile
- README.rst
- benchmark/locustfile.py
- docs/conf.py
- pytest.ini
- reana/__init__.py
- reana/cli.py
- reana/k8s_utils.py
- setup.py
- tests/test_cli.py
- tests/test_version.py
> global: Black support

- reana/cli.py
Addresses reanahub/reana-auth-krb5#1.
> cli: addition of reana-auth-{krb5,vomsproxy}

- .travis.yml
- CHANGES.rst
- Makefile
- helm/reana/README.md
- helm/reana/templates/_helpers.tpl
- helm/reana/templates/announcement-config.yaml
- helm/reana/templates/cronjobs.yaml
- helm/reana/templates/ingress.yaml
- helm/reana/templates/kerberos-config.yaml
- helm/reana/templates/reana-cache.yaml
- helm/reana/templates/reana-db.yaml
- helm/reana/templates/reana-mail.yaml
- helm/reana/templates/reana-message-broker.yaml
- helm/reana/templates/reana-server.yaml
- helm/reana/templates/reana-shared-persistent-volume.yaml
- helm/reana/templates/reana-ui.yaml
- helm/reana/templates/reana-wdb.yaml
- helm/reana/templates/reana-workflow-controller.yaml
- helm/reana/templates/roles.yaml
- helm/reana/templates/secrets.yaml
- helm/reana/templates/serviceaccount.yaml
- helm/reana/templates/uwsgi-config.yaml
- helm/reana/values.yaml
- reana/cli.py
* Use the Helm release namespace as the namespace where
REANA will be running. Passes this configuration down to
REANA-Workflow-Controller which will take care of creating
all runtime pods so they run on the desired namespace
(closes #274).
* Allows having two different namespaces for infrastructure and runtime
pods (closes #268).
> config: use centrally configured k8s namespace

- reana/reana_dev/git.py
- reana/reana_dev/utils.py
> cli: add git-upgrade-shared-modules command

- reana/reana_dev/cluster.py
Adds new `cluster-stop` and `cluster-start` commands.  Amends help
messages for other `cluster-*` commands for consistency.
> cli: addition of cluster-stop and cluster-start commands

- setup.py
Declares dependency on `packaging` module, fixing `reana-dev
git-clone` issues on from-scratch installations. Closes #382.
> installation: packaging dependency

- helm/reana/values.yaml
- reana/reana_dev/cluster.py
Allows excluding reana-ui from cluster deploy.
closes reanahub/reana-ui#114
depends on https://github.com/reanahub/pytest-reana/pull/65
> helm: enable reana-ui by default

- reana/config.py
Adds Docker images to prefetch for the `reana-demo-bsm-search` example
following up its 1.0.0 release.
> config: prefetch docker images for BSM demo

- reana/reana_dev/git.py
> cli: don't autodiscover version when passed as arg

- helm/reana/Chart.yaml
Declares support for Kubernetes 1.19 that was successfully tested
using Kind 0.9.0.
> helm: Kubernetes 1.19

- index.yaml
As the last step of cleaning up the [current REANA releases](https://github.com/reanahub/reana/releases) we are missing to remove https://github.com/reanahub/reana/releases/tag/reana-0.7.0-alpha.1 which was created by the CR GitHub action and use https://github.com/reanahub/reana/releases/tag/0.7.0-alpha.1 which is correctly named.
To do:
> index.yaml: fix 0.7.0-alpha.1 release link

- reana/reana_dev/docker.py
- reana/reana_dev/release.py
- reana/reana_dev/utils.py
> cli: convert docker-build tag auto to semver2

- reana/reana_dev/utils.py
* Currently, if the line selector is not found in the file
the `line` variable is empty. This triggers a wrong update
of any line in the file that matches the `find` variable,
typically many.
> cli: replacing strings better error messages

- reana/reana_dev/git.py
- reana/reana_dev/utils.py
> cli: fix git-upgrade-shared-modules

- reana/config.py
- reana/reana_dev/cli.py
- reana/reana_dev/git.py
- reana/reana_dev/utils.py
Adds new `--base` option to all `git-*` commands to facilitate working
against different git base branch, such as `maint-0.7`.
Adds new command `git-checkout` that allows to switch branches in many
components at one ago.
Renames old `git-checkout` to `git-checkout-pr` accordingly.
Fixes some parallel flake8-discovered warnings.
Closes #413.
> cli: new `--base` option for `git-*` commands

- scripts/prefetch-images.sh
Adds new script `prefetch-images.sh` to solve researcher-style local
installation troubles on slow network connections. Closes #431
> scripts: prefetch images

- reana/reana_dev/git.py
- reana/version.py
- tests/benchmark/locustfile.py
Adds new options to git-log command to show patch or to pass any
wanted argument.
Examples:
$ reana-dev git-log -c CLIENT -n 5 -p --paginate
$ reana-dev git-log -c CLIENT -n 3 --stat --oneline
$ reana-dev git-log -c CLIENT --graph --all
$ reana-dev git-log -c CLIENT master..maint-0.7
$ reana-dev git-log -c CLUSTER -c CLIENT master..maint-0.7 \
--exclude-components r-a-vomsproxy,r-a-krb5
> cli: richer git-log command

- reana/config.py
- reana/reana_dev/cli.py
- reana/reana_dev/utils.py
- reana/reana_dev/wiki.py
> cli: add command to generate build status wiki

- reana/reana_dev/git.py
We have a few components without `maint-0.7` branch, which results in:
```
$ reana-dev git-upgrade --base maint-0.7
...
[2020-11-09T14:13:33] reana-auth-krb5: git fetch upstream
[2020-11-09T14:13:35] reana-auth-krb5: git checkout maint-0.7
error: pathspec 'maint-0.7' did not match any file(s) known to git
[2020-11-09T14:13:35] reana-auth-krb5: Command 'git checkout maint-0.7' returned non-zero exit status 1.
```
With this PR one gets:
```
$ reana-dev git-upgrade --base maint-0.7
...
[2020-11-09T14:15:00] reana-workflow-engine-serial: git push origin maint-0.7
Everything up-to-date
[2020-11-09T14:15:02] reana-workflow-engine-serial: git checkout -
Already on 'maint-0.7'
Your branch is up to date with 'upstream/maint-0.7'.
[2020-11-09T14:15:02] reana-auth-krb5: Missing branch maint-0.7, …
```
> cli: git-upgrade skip on missing branch

- reana/reana_dev/git.py
Adds `--exclude-components` option to many `git-*` commands, allowing
to do things like:
$ reana-dev git-status -c CLIENT -c CLUSTER --base maint-0.7 \
--exclude-components r-a-vomsproxy,r-a-krb5
> cli: `git-*` commands completed with `--exclude-components` option

- reana/reana_dev/utils.py
> utils: fix `fetch_latest_pypi_version` function

- helm/reana/templates/ingress.yaml
* Helm 3.4 warns about this, more in the [docs](https://kubernetes.io/docs/concepts/services-networking/ingress/).
> helm: update Ingress API for k8s>=1.19

- helm/reana/README.md
- helm/reana/templates/ui-config.yaml
- helm/reana/values.yaml
closes #472
By default, user confirmation is enabled, to disable it add env var `REANA_USER_CONFIRMATION: false` in `values.yaml`:
```diff
@@ -60,6 +77,7 @@ components:
image: reanahub/reana-server:0.7.1
environment:
REANA_MAX_CONCURRENT_BATCH_WORKFLOWS: 30
+      REANA_USER_CONFIRMATION: false
uwsgi:
processes: 6
threads: 4
```
> helm: expose user_confirmation flag to ui config

- reana/reana_dev/git.py
Adds `--exclude-components` option to all `reana-dev git-*` commands.
Allows to run useful branch-specific commands such as:
$ reana-dev git-upgrade -c CLUSTER -c CLIENT --base maint-0.7 \
--exclude-components r-a-krb5,r-a-vomsproxy
> cli: `--exclude-components` for `git-*` commands

- CHANGES.rst
- reana/config.py
- reana/reana_dev/run.py
- tests/test_cli.py
Extends `reana-dev run-example` to be able to specify compute backends, making it easier to test https://github.com/reanahub/reana-job-controller/issues/304 and allow richer CI scnearios:
```
$ reana-dev run-example --compute-backend ALL --timeout 1800
[2021-03-09T15:17:02] : Running the following matrix:
Demos: ['reana-demo-worldpopulation', 'reana-demo-helloworld', 'reana-demo-root6-roofit', 'reana-demo-atlas-recast']
Workflow engines:['serial', 'yadage', 'cwl']
Compute backends: ['kubernetes', 'htcondorcern', 'slurmcern']
Number of workflows: 36
```
Closes https://github.com/reanahub/reana-job-controller/issues/304.
Caveats:
- ~~Slow: Non-parallelisable for the moment~~
- ~~`TIMEOUT` needs to be increased due to HTCondor and Slurm taking longer to execute~~
> cli: enrich run-example to run full test matrix

- reana/reana_dev/cluster.py
- reana/reana_dev/docker.py
- reana/reana_dev/run.py
From `click 8.0.0`, `default` must be a list or a tuple for options that are `multiple=True`.
https://click.palletsprojects.com/en/8.0.x/options/?highlight=multiple#multiple-options
closes #503
> cli: remove click option default when multiple=True

- helm/reana/templates/reana-message-broker.yaml
- reana/reana_dev/cluster.py
closes https://github.com/reanahub/reana/issues/500
Testing Instructions without PR:
1. `max parallel running  workflows helm variable` -> 1
2. Launch n workflows so that some workflows remain in the ready queue.
3. For ex: If n=3, While the 1st is running and 2nd and 3rd are in the queue in `ready state`, kill the queue pod (`message-broker`)
5. The Pod will be restarting again and check `/var/lib/rabbitmq/mnesia`, there will be files with the new name and our previous data is gone.
Testing Instructions with this PR and https://github.com/reanahub/reana-commons/pull/263:
1. `max parallel running  workflows helm variable` -> 1
2. Rebuild the message broker and load the new image.
3. Before killing, using the UI, create a new durable queue and publish a durable message to see if the queue …
> Mount volume for persistance storage of rabbitmq data

- helm/reana/templates/reana-config.yaml
- helm/reana/templates/reana-server.yaml
Introduce scheduler configuration in reana-config.
closes reanahub/reana-server#356
1. Checkout reanahub/reana-server#356 PR set
2. Observe in a terminal the output of `kubectl logs deployment/reana-server scheduler -f`
3. Run multiple workflows and observe how priorities get lower when there're already other workflows running.
```console
2021-06-09 12:51:59,822 | root | MainThread | INFO | Starting queued workflow: {'user': '00000000-0000-0000-0000-000000000000', 'workflow_id_or_name': 'roofit.5', 'parameters': {'input_parameters': {}, 'operational_options': {}}, 'priority': 97}
...
2021-06-09 12:52:04,441 | root | MainThread | INFO | Starting queued workflow: {'user': '00000000-0000-0000-0000-000000000000', 'workflow_id_or_name': 'roofit.6', 'parameters': {'input_parameters': {}, …
```
> helm: make ui configmap more generic

- helm/reana/Chart.yaml
Declares support for Kubernetes 1.21 that was successfully tested
locally using Kind 0.11.1.
> helm: Kubernetes 1.21

- helm/reana/templates/cronjobs.yaml
Otherwise it does not have permission to fetch nodes info.
```console
Something went wrong while generating the status report:                                                                      
(403)                                                                                                                         
Reason: Forbidden                                                                                                             
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'X-Kubernetes-Pf-Flowschema-Uid': 'c0b0df96-efa1-4474-864d-1a1fefbfbe7a', 'X-Kubernetes-Pf-Prioritylevel
-Uid': 'f8e92979-82ef-48ae-8163-e0ca06a57e60', 'Date': 'Tue, 29 Jun 2021 08:26:03 GMT', …
```
> helm: add svc account to status report cronjob

- reana/reana_dev/run.py
When running CI build via `reana-dev run-ci`, the Snakemake example was
also run, even though the Snakemake workflow engine isn't fully
supported yet. This made each `run-ci` test to fail.
This commit fixes the issue by introducing a new `-w` option that allows
to specify desired workflow engine for the CI test, similarly as in the
`run-example` command.  Until Snakemake is fully supported, developers
can use `-w cwl -w serial -w yadage` to test all the currently supported
workflow engines.
> cli: run-ci -w option addition

- reana/reana_dev/git.py
- reana/reana_dev/utils.py
- tests/test_utils.py
Closes #516 
Expected behavior:
1. `reana-dev git-create-release-commit -c reana` command will bump all found version files (Helm, Py, JS, OpenAPI) to its next version 
2. `-v` will **enforce the specified version** on all version files (PEP440 will be converted to SemVer2 when needed and vice-versa). 
Behavior examples:
- `reana-dev git-create-release-commit -c reana` will automatically bump Helm (SemVer2) and Python (PEP440). For git tags - SemVer2
- `reana-dev git-create-release-commit -c reana-server` will automatically bump Python and OpenAPI (PEP440). For git tags - PEP440
- `reana-dev git-create-release-commit -c reana -v 0.8.1-alpha.1` will bump Helm to 0.8.1-alpha.1 and Python to 0.8.1a1. For git tags - 0.8.1-alpha.1 (SemVer2)
- `reana-dev git-create-release-commit -c …
> git-create-release-commit bumps all available versions in the components

- helm/reana/templates/reana-db.yaml
Enriches `reana-db` helm template to define explicitly the max number
of allowed DB connections. The default value is 100 which may not be
enough for installations launching many concurrent
workflows. Increasing it to 300. Moreover, having the number
explicitly defined in the template will allow site administrators to
easily customise it further.
> helm: explicit number of DB connections

- CHANGES.rst
- helm/reana/README.md
closes reanahub/reana-server#404
Merge after https://github.com/reanahub/reana-server/pull/412 (to be able to test)
> helm: set reana-server API limiter configs

- scripts/reana_bench.py
- adds two new commands: submit and start
- launch works as before, performing both submit and start
closes #572
> benchmark: split launch into submit and start commands

- scripts/reana_bench.py
- improves execution progress plot, now using absolute date values instead of relative time values;
- removes _pre_processed_results function as epoch time is not needed anymore for execution progress plot;
- adds "--interval" parameter to "analyze" command to customize execution progress plot datetime axis;
- renames "*_processed_results.csv" to "*_analyzed_results.csv" to align naming with "analyze" command;
- adds new column "workflow_number" in _derive_metrics function in "analyze" to be able to filter data by workflow range, now plots can be generated with subset of workflows only;
- in case of out of bound workflow range, workflows in the range will be included without throwing an error;
- plots files are generated with a suffix that includes workflow range.
addresses #573
> benchmark: improve execution progress plot, add workflow range to analyze

- helm/reana/templates/reana-db.yaml
closes https://github.com/reanahub/reana-message-broker/issues/41
Uses PVC for db deployment if the storage backend is not `hostpath`:
- once deployed locally it will continue using `hostPath`
- once deployed with e.g. `cephfs` shared storage it will use `reana-shared-volume` PVC for volumes
> helm: use PVC for db deployment

- helm/reana/templates/reana-message-broker.yaml
closes https://github.com/reanahub/reana-message-broker/issues/41
To test:
- Redeploy the cluster with [NFS provisioner](https://github.com/reanahub/reana-commons/pull/306) and `REANA_MAX_CONCURRENT_BATCH_WORKFLOWS: 1`
- Check the `/var/reana` locally, `rabbitmq` folder shouldn't be there:
- Check if `rabbitmq` files are in NFS PVC:
```
reana ❯ kubectl exec -it reana-dev-storage-nfs-server-provisioner-0  -- bash
bash-5.0# cd /export/pvc-77e7cbb4-7dce-4a97-b7f0-6305a6a7c684/
bash-5.0# ls
config  rabbitmq  users  uwsgi
```
- Check RabbitMQ pod logs (note there is a line about db init):
```
reana ❯ kubectl logs reana-message-broker-0 | grep database
database dir   : /var/lib/rabbitmq/mnesia/rabbit@localhost
2021-10-22 11:51:35.616 [info] <0.274.0> Running boot step database defined by app …
```
> helm: use PVC for rabbitmq data

- scripts/reana_bench.py
closes #584
If during the `start` command, an error happens in the middle we lost started results for previously started workflows. This PR fixes it.
How to test:
Use some fast workflow like `helloworld` demo.
1. Create and upload 3 workflows:
```console
$ ./reana_bench.py submit -w test -n 1-3 
```
2. Start the second workflow: 
```console
$ ./reana_bench.py start -w test -n 2-2  
```
`test_started_results.csv` should look like this:
```csv
name,asked_to_start_date
test-2,2021-11-12T13:02:29
```
3. Collect results of the second workflow:
```console
$ ./reana_bench.py collect -w test -f 
```
Check `test_collected_results.csv`:
```csv
test-3,1,2021-11-12T13:02:16,,,created,,2021-11-12T13:05:26 …
```
> benchmark: ignore start errors and save started workflows results

- reana/reana_benchmark/cli.py
- reana/reana_benchmark/monitor.py
This PR introduces `monitor` command to the benchmark. It will collect all defined metrics (check code for details), sleep for a defined time in seconds, and repeat the same process until is terminated *manually*. Results are saved to a JSON file to be used in the `analyze` command later.
closes #574
How to test:
1. (*optional*) Launch some workflows `reana-benchmark launch -w monitor-test -n 1-20` (**not**  `helloworld` as they are too fast, `atlas-demo` is okay);
2. Right after workflows are started, start a monitor command `reana-benchmark monitor --sleep 5 -w monitor-test`;
3. When workflows are finished (or around that time), terminate the command using Ctrl+C;
4. Check JSON output in `monitor-test_monitored_results.json`, you will see some metrics (currently 2) and timestamps when …
> benchmark: add monitor command

- reana/reana_benchmark/analyze.py
- reana/reana_benchmark/config.py
- adds point to indicate whatever workflow finished or failed in execution_progress plot;
- use the same colours in execution_status and execution_progress plots;
- histogram plots have only one label so colours harmonization is not applied there, colours are generated automatically, usually blue.
closes #588 
How to test:
1. If you don't have already collected results from previous benchmarks you can get new ones:
```console
$ reana-benchmark launch -w color -n 1-10
$ reana-benchmark collect -w color
```
OR, you can use this CSV content and save it under `color_collected_results.csv`:
```csv
color-3,1,2021-11-16T10:24:12,2021-11-16T10:24:39,,running,2021-11-16T10:24:23,2021-11-16T10:24:47 …
```
> benchmark: harmonize colours between plots

- reana/reana_benchmark/analyze.py
- reana/reana_benchmark/cli.py
- reana/reana_benchmark/config.py
- reana/reana_benchmark/utils.py
Adding `datetime_range` option to `analyze` command to be able to "zoom" into the `execution_progress` plot. The new option is similar to the `interval` option we already have, it acts as a customizer to a plot.
closes #583
How to test:
1. Save dummy CSV file as `datetime-range_collected_results.csv`:
```csv
color-3,1,2021-11-16T10:24:12,2021-11-16T10:24:39,,running,2021-11-16T10:24:23,2021-11-16T10:25:47
color-2,1,2021-11-16T10:24:11,2021-11-16T10:24:37,2021-11-16T10:25:44,finished,2021-11-16T10:24:23,2021-11-16T10:25:47
color-1,1,2021-11-16T10:24:11,2021-11-16T10:24:35,2021-11-16T10:25:42,failed,2021-11-16T10:24:23,2021-11-16T10:25:47
color-4,1,2021-11-16T10:24:12,,,queued,2021-11-16T10:24:23,2021-11-16T10:25 …
```
> benchmark: add datetime range plot parameter to analyze command

- reana/reana_benchmark/analyze.py
- reana/reana_benchmark/cli.py
- in addition, add one more tick on x-axis if interval is approximated to ensure that all points are covered;
- change time interval from minutes to seconds.
closes #590
How to test:
1. If you don't have already collected results from previous benchmarks you can get new ones:
```console
$ reana-benchmark launch -w time -n 1-10
$ reana-benchmark collect -w time
```
OR, you can use this CSV content and save it under `time_collected_results.csv`:
```csv
time-3,1,2021-11-16T10:24:12,2021-11-16T10:24:39,,running,2021-11-16T10:24:23,2021-11-16T10:24:47
time-2,1,2021-11-16T10:24:11,2021-11-16T10:24:37,2021-11-16T10:24:44,finished,2021-11-16T10:24:23,2021-11-16T10:24:47 …
```
> benchmark: approximate x-axis interval for execution progress plot

- CHANGES.rst
- helm/reana/README.md
- helm/reana/templates/uwsgi-config.yaml
- helm/reana/values.yaml
- by default, log all HTTP requests
- allow logging only HTTP error requests (status code 4xx and 5xx)
closes reanahub/reana-server#417
- Force uWSGI (Production mode):
```diff
diff --git a/helm/reana/templates/reana-server.yaml b/helm/reana/templates/reana-server.yaml
index ab43b8b..6be9538 100644
--- a/helm/reana/templates/reana-server.yaml
+++ b/helm/reana/templates/reana-server.yaml
@@ -37,7 +37,7 @@ spec:
ports:
- containerPort: 5000
name: http
-        {{- if .Values.debug.enabled }}
+        {{- if false }}
command: ["/bin/sh", "-c"]
args: ["invenio run -h 0.0.0.0 -p 5000"]
tty: true
```
- Play with different configurations and verify that logs are properly displayed
- To force 4xx, just navigate to /api/foo (`curl -k https://localhost:30443/api/foo`)
- To force 5xx, you can raise …
> helm: make http logging configurable

- reana/reana_dev/release.py
- reana/reana_dev/utils.py
closes #497
It's a bit challenging to test this PR without performing an actual chart release from a `maint` branch. I've added a `--dry-run` flag to `release-helm` so one could first verify the commands to be run.
> cli: add target commit for release to `release-helm`

- scripts/run_cwl_conformance_tests.py
closes https://github.com/reanahub/reana-workflow-engine-cwl/issues/188
Added a new a script which:
- downloads CWL files for each of the specification version
- runs and parses the output of conformance tests
- creates a markdown output from the results and stores it in a file
- lists where the CWL files are stored to access generated badges and detailed tests report
Here is how the output looks like:
```
...
2022-01-11 15:36:35,716 | Storing CWL conformance tests output to a file
2022-01-11 15:36:35,717 | Final markdown output:
REANA 0.8.0 tested on 2022-01-11
- 2 tests passed
- 1 failures
- Test [6/197] initworkdir_expreng_requirements: Test InitialWorkDirRequirement ExpressionEngineRequirement.engineConfig feature
- 0 unsupported features
REANA 0.8.0 tested on 2022-01-11
- 2 tests …
```
> scripts: added CWL conformance test runner

- CHANGES.rst
- helm/reana/README.md
- helm/reana/values.yaml
closes reanahub/reana-server#443
> helm: add rate limit env variable to launch workflow

- helm/configurations/values-dev.yaml
Issue as described by @mdonadoni : 
`for each launch request  two requests are actually done (OPTIONS followed by POST) and both of them count towards the rate limit. Given that the limit is "1/5 second", the POST request is always blocked and returns an error`
This PR modifies the rate limiter value to be more permissive for local developments
> helm: relax rate limiter value for local developments

- CHANGES.rst
- reana/reana_dev/utils.py
Closes #613
How to test:
1. Patch `fetch_latest_pypi_version` in [utils.py](https://github.com/reanahub/reana/blob/4a212c7f5be37e63a98db8984f2df898c060c0bd/reana/reana_dev/utils.py#L378) to return a custom version number:
```diff
def fetch_latest_pypi_version(package):
"""Fetch latest released version of a package."""
import requests
+    if package == "reana-commons":
+        return "0.10.3"
+
pypi_rc_info = requests.get("https://pypi.python.org/pypi/{}/json".format(package))
return sorted(pypi_rc_info.json()["releases"].keys(), key=Version)[-1]
```
2. Run `reana-dev git-upgrade-shared-modules -c . --use-latest-known-tag` in one of the components, e.g. reana-server
Expected result: In `setup.py` the upper-bound is set to `0.11.0`
```diff
- …
```
> cli: fix upper-bound in `git-upgrade-shared-modules`

- reana/reana_dev/run.py
> cli: make nicer report message for run-example command

- CHANGES.rst
- helm/reana/Chart.yaml
Declares support for Kubernetes 1.24 that was successfully tested
locally using Kind 0.14.
> helm: Kubernetes 1.24

- CHANGES.rst
- helm/reana/Chart.yaml
Declares support for Kubernetes 1.25 that was successfully tested locally using Kind 0.15.
> helm: Kubernetes 1.25

- reana/config.py
- reana/reana_dev/client.py
Useful for commands such as `reana-dev git-fetch -c CLIENT` etc.
Modifies `reana-dev client-install` accordingly.
> config: add reana-client-go to CLIENT repositories

- helm/reana/templates/cronjobs.yaml
Sets a forbidding concurrency policy for all cronjobs so that they would not be allowed to start if an old cronjob instance is still running.
Useful to prevent scheduling new cron job pods when the past cron job pods are not yet finished e.g. due to troubles with shared filesystem.
> helm: set concurrency policy for all cronjobs

- helm/reana/templates/uwsgi-config.yaml
Enable support for keep-alive in uWSGI's configuration. This fixes an
issue with Traefik sporadically returning 500 or 502 status codes, with
logs reporting errors such as `http: server closed idle connection` and
`write: broken pipe`.
See
https://uwsgi-docs.readthedocs.io/en/latest/HTTP.html#http-keep-alive
for more information about keep-alive in uWSGI.
How to test:
1. Create a new workflow: `reana-client create -w workflow`
2. Run many concurrent uploads: ``for i in `seq 50`; do reana-client upload -w workflow.1 &; done; wait``
> uwsgi: enable keep-alive support

- CHANGES.rst
- LICENSE
- docs/conf.py
- helm/reana/Chart.yaml
Declares support for Kubernetes 1.26 that was successfully tested locally using Kind 0.17 with the image
`kindest/node:v1.26.0@sha256:691e24bd2417609db7e589e1a479b902d2e209892a10ce375fab60a8407c7352`.
> helm: Kubernetes 1.26

- CHANGES.rst
- helm/reana/templates/uwsgi-config.yaml
Fixes memory consumption of the "uWSGI http 1" process that was rising above 8 GiB on systems like Fedora 37 (locally) and Fedora CoreOS 36 (in the cloud) due to very high file descriptor limits (`fs.nr_open = 1073741816`). See <https://github.com/kubernetes-sigs/kind/issues/2175> and <https://github.com/unbit/uwsgi/issues/2299>.
Sets the uWSGI `max-fd` value to 1048576 as per
<https://github.com/kubernetes-sigs/kind/pull/1799/files>. If need be, we can make it configurable via Helm chart values later.
> uwsgi: fix memory consumption related to max-fd

- CHANGES.rst
- helm/reana/Chart.yaml
- setup.py
Declares support for Kubernetes 1.27 that was successfully tested locally using Kind 0.18 with the image
`kindest/node:v1.27.1@sha256:9915f5629ef4d29f35b478e819249e89cfaffcbfeebda4324e5c01d53d937b09`.
> helm: Kubernetes 1.27

- CHANGES.rst
- helm/reana/templates/cronjobs.yaml
Add missing environment variables that caused cronjobs to fail to
connect to the database when REANA is deployed with a non-default
namespace or prefix.
Closes #711
> helm: add missing env variables to cronjobs

- helm/reana/templates/cronjobs.yaml
Add `REANA_SECRET_KEY` and `REANA_ADMIN_ACCESS_TOKEN` environment
variables to cronjobs. The former is needed to decrypt the tokens in the
database, the latter is needed to execute `reana-admin` commands.
Closes reanahub/reana-server#489
> cronjobs: add secret key and admin access token to environment

- helm/reana/templates/cronjobs.yaml
- helm/reana/templates/reana-server.yaml
- helm/reana/values.yaml
Avoid using `default` when setting boolean values, as `false` is
interpreted as an empty value.
Closes #725
How to test:
1. Set `smtp_starttls` and `smtp_ssl` to different values, like:
```yaml
notifications:
enabled: true
email_config:
smtp_starttls: false
```
2. Check that the values are correctly set inside the pods:
```
kubectl exec deployment/reana-server -- env | grep -i smtp
```
> helm: fix SSL/STARTTLS configuration

- helm/reana/templates/reana-server.yaml
Adds an env variable that contains the maximum number of days for which an interactive session can stay inactive before being automaticallly closed.
Closes reanahub/reana-client#657
> helm: add env variable for session inactivity to server

- setup.py
Bump the upper pin on PyYAML in order to support v6, to be consistent
with the other REANA components.
Closes reanahub/reana-commons#399
> setup: bump upper pin of PyYAML

- CHANGES.rst
- helm/reana/Chart.yaml
Declares support for Kubernetes 1.28 that was successfully tested locally using Kind 0.20 with the image
`kindest/node:v1.28.0@sha256:b7a4cad12c197af3ba43202d3efe03246b3f0793f162afb40a33c923952d5b31`.
> helm: Kubernetes 1.28

- CHANGES.rst
- helm/reana/templates/reana-server.yaml
Avoid using `/bin/sh -c` to run uwsgi, as that breaks signal
propagation.
Closes reanahub/reana-job-controller#347
**How to test:**
- Check out the following PRs:
- https://github.com/reanahub/reana/pull/747
- https://github.com/reanahub/reana-server/pull/629
- https://github.com/reanahub/reana-workflow-controller/pull/526
- Deploy the cluster in non-debug mode
- Delete reana-server/reana-workflow-controller pods
**Expected behaviour:**
The pods are terminated "fast", that is without waiting the standard k8s grace period of 30s, and the logs show:
rest-api:
```
[...]
Gracefully killing worker 1 (pid: 16)...
Gracefully killing worker 2 (pid: 18)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
goodbye to uWSGI.
VACUUM: unix socket /tmp/stats.socket (stats) removed.
``` …
> helm: fix graceful shutdown for reana-server

- reana/config.py
- reana/reana_dev/git.py
- reana/reana_dev/utils.py
> cli: add git-upgrade-requirements

- reana/reana_dev/git.py
> reana-dev: update git commands to use gh CLI

- CHANGES.rst
- reana/config.py
- reana/reana_dev/python.py
Improves the `python-run-tests` command to create Python-3.8 based virtual environments to use the same version as container images.
Updates `pip` before installing each component in order to speed up the dependency resolution for certain cluster components.
Allows execution of selected pytests only by passing over `PYTEST_ADDOPTS` environment variable.
Switches to using `run-tests.sh` to execute pytests in individual components which takes care of the DB setup at the source.
Allows excluding certain Python components such as `-c CLUSTER --exclude-components r-j-controller` on macOS.
Example:
```
$ PYTEST_ADDOPTS=tests/test_version.py reana-dev python-unit-tests -c ALL -k
```
Closes #755.
> dev: improve python-run-tests execution

- .github/workflows/ci.yml
- reana/reana_dev/cli.py
- reana/reana_dev/docker.py
- reana/reana_dev/release.py
- reana/reana_dev/utils.py
- utils: remove unused code
- docker-push: add registry option
- docker-push: add image-name option
- release-docker: add registry option
- docker-build: add platform option
- release-docker: add platform option
Closes reanahub/reana#752
> docker: add registry option

- CHANGES.rst
- helm/reana/Chart.yaml
- helm/reana/values.yaml
- reana/reana_dev/git.py
- reana/version.py
- scripts/prefetch-images.sh
- setup.py
- git-create-release-branch: fix version detection
- release: 0.9.2
TODO:
> release: 0.9.2

- reana/reana_dev/git.py
Change the `git-submodule --update` command to delete from the `modules`
folder of the cluster components the files that are not present in the
original directories, reflecting a more accurate status of the shared
modules.
Closes #761.
> dev: delete extra file when running git-submodule --update

- helm/reana/Chart.yaml
Declare support for Kubernetes 1.29 that was successfully tested locally using Kind 0.21.
> build(helm): add support for Kubernetes 1.29

- helm/reana/README.md
- helm/reana/templates/reana-config.yaml
> feat(helm): add value to customise URL of privacy notice (#778)

- helm/configurations/values-dev.yaml
- helm/reana/README.md
- helm/reana/templates/reana-db.yaml
- helm/reana/values.yaml
- reana/config.py
- reana/reana_dev/python.py
- feat(helm): add value to customise PostgreSQL docker image (#774)
- feat(helm): use PostgreSQL 14.10 in local dev deployment (#774)
Closes #773 
Closes #744
> feat(helm): add value to customise PostgreSQL docker image (#774)

- README.md
Remove the mention of Gitter for chat that we don't use since a few years. Keep recommending Forum and Mattermost as the two main communication channels.
> docs(chat): remove Gitter

- reana/config.py
- reana/reana_dev/git.py
- reana/reana_dev/utils.py
Changes `reana-dev git-create-release-commit` behaviour to also update the container image label version when releasing cluster components.
> fix(reana-dev): update container image labels when releasing (#765)

- helm/reana/README.md
- helm/reana/templates/ingress.yaml
- helm/reana/templates/reana-workflow-controller.yaml
- helm/reana/values.yaml
> fix(helm): use ingressClassName instead of deprecated annotation (#794)

- helm/reana/Chart.yaml
Declare support for Kubernetes 1.30 that was successfully tested locally using Kind 0.23.
> build(helm): add support for Kubernetes 1.30 (#799)

- AUTHORS.md
- helm/reana/templates/reana-workflow-controller.yaml
Closes reanahub/reana-workflow-controller#587
> feat(helm): allow cluster administrator to configure ingress host (#804)

- AUTHORS.md
- reana/config.py
- reana/reana_dev/cluster.py
This pull request adds the new `compute4punch` compute backend to the list of available compute backends. The `compute4punch` compute backend is currently implemented in https://github.com/reanahub/reana-job-controller/pull/430.
> Add compute4punch compute_backend

- .github/workflows/ci.yml
- setup.py
BREAKING CHANGE: drop support for Python 3.6 and 3.7
Closes reanahub/reana#784
> build(python): drop support for Python 3.6 and 3.7 (#793)

- AUTHORS.md
- helm/reana/templates/reana-db.yaml
- helm/reana/templates/reana-message-broker.yaml
- reana/reana_dev/cluster.py
Current port mapping from Kubernetes service to localhosts for RabbitMQ debugging does not work (RabbitMQ has a nice UI that allows inspecting queues and messages). The reason is that `reana-message-broker` uses `ClusterIP` service instead of `NodePort`, which does not allow access from outside of the cluster (`reana-mail` uses NodePort and works fine). I can think of two ways of fixing it - either delete broken code from `cluster.py` and use `kubectl port-forward`, or add additional debug `NodePort` service to Helm chart (we already have `debug.enabled` flag). This PR implements the latter, as it simplifies running REANA cluster in debugging mode.
Also adding debug service for PostgreSQL which would allow connecting to it via PostgreSQL client on host machine.
Kubernetes services before: …
> fix(helm): add NodePort services for debugging (#812)

- helm/configurations/values-dev.yaml
- helm/reana/README.md
- helm/reana/templates/cronjobs.yaml
- helm/reana/templates/database-config.yaml
- helm/reana/templates/database-secrets.yaml
- helm/reana/templates/pgbouncer-config.yaml
- helm/reana/templates/pgbouncer-secrets.yaml
- helm/reana/templates/pgbouncer.yaml
- helm/reana/templates/reana-db.yaml
- helm/reana/templates/reana-server.yaml
- helm/reana/templates/reana-workflow-controller.yaml
- helm/reana/templates/secrets.yaml
- helm/reana/values.yaml
> feat(helm): add support for pgbouncer (#818)

- helm/reana/templates/cronjobs.yaml
- helm/reana/templates/reana-workflow-controller.yaml
Closes reanahub/reana-server#694
> fix(helm): allow interactive-session-cleanup job to access RWC (#820)

- .github/workflows/ci.yml
- helm/reana/Chart.yaml
- reana/reana_dev/utils.py
Declare support for Kubernetes 1.31 that was successfully tested locally using Kind 0.24.
> build(helm): add support for Kubernetes 1.31

- AUTHORS.md
- helm/reana/Chart.yaml
- reana/config.py
- reana/reana_dev/cluster.py
- reana/reana_dev/utils.py
build(helm): add support for Kubernetes 1.31 (#822)
ci(python): pin setuptools 70 (#822)
feat(config): add Compute4PUNCH backend (#780)
Note: The merge commit removes the changes related to pinning
`setuptools` to version 70, because this was only necessary for the
`maint-0.9` branches.
> chore(master): merge maint-0.9

- AUTHORS.md
- reana/reana_dev/run.py
- tests/test_cli.py
Run-example now uses the test files in the specification file to check the correctness of the results (by running the test command).
> feat(reana-dev): change run-example to use gherkin-parser module (#817)

- reana/reana_dev/cluster.py
Similar [issue](https://github.com/reanahub/reana/issues/654) happened to me using `reana-dev` tool with fresh `kind` install. `kind` pulls the latest image version, but the version does not match `kubeVersion` in Helm chart, which causes error on Helm chart deployment.
Though Helm chart is now upgraded and accepts newest image version, at some point in time discrepancy will happen again.  `kindest/node` image version can just be pinned (should be updated together with Helm chart) and can be allowed to customize as a CLI option.
> feat(reana_dev): customize kind image version (#811)

- helm/reana/Chart.yaml
I have realized that our `traefik` dependency is from 3 years ago. Updating the treaefik dependency resolved the linting error. I tested it with 5 different workflows and it seems to be working fine.
closes (#798)
> feat(helm): upgrade traefik (#832)

- helm/reana/README.md
- helm/reana/templates/reana-server.yaml
- helm/reana/templates/reana-workflow-controller.yaml
- helm/reana/values.yaml
> feat(dask): make dask autoscaler configurable

- helm/configurations/values-dev.yaml
- helm/reana/README.md
- helm/reana/templates/secrets.yaml
- helm/reana/values.yaml
- reana/reana_dev/cluster.py
- **fix(helm): set `fsGroup` to zero for local opensearch deployment (#843)**
- **fix(helm): support OpenSearch deployment in non-default namespace (#843)**
- **fix(helm): avoid re-defining REANA_OPENSEARCH_PASSWORD (https://github.com/reanahub/reana/pull/843)**
> fix(helm): improve opensearch deployment

- helm/reana/Chart.yaml
Since Kubernetes 1.22, there was never a big need to actually upgrade REANA source code to make it work on new Kubernetes releases. (This is thanks to the fact that REANA uses pretty stable Kubernetes API internally.) This commit therefore releases the upper boundary check on the supported Kubernetes versions in order to be more welcoming to future Kubernetes upgrades, alleviating the need to manually bump the supported version number.
> feat(helm): release check on most-supported Kubernetes version

- .github/ct.yaml
Our current helm linting github action looks for `main` branch. However, we are using `master` branch. We should explicitly specify `helm` in `target-branch` field.
> ci(helm): configure target branch name for helm linting

- helm/reana/values.yaml
This PR adds the collection of logs for Dask pods, namely scheduler and workers.
Closes reanahub/reana-workflow-controller#610
> feat(helm): collect logs from Dask pods 

- reana/reana_dev/git.py
For commits created by `reana-dev git-upgrade-shared-modules` and `reana-dev git-upgrade-requirements` commands, use "chore" rather than "build" conventional commit scope, so that these commits won't appear in the release news message.
The bug fixes or new features that are brought by upgrades are announced in the release news in another way, such as when a feature needs the new shared package or an upgraded version of dependency. The pre-release version bumps can therefore go without a release news item.
> fix(reana-dev): use chore commit scope when bumping dependencies

- reana/reana_dev/cluster.py
- reana/reana_dev/kind.py
- reana/reana_dev/run.py
- reana/reana_dev/utils.py
- scripts/prefetch-images.sh
Add option `--kubernetes` to several `reana-dev` commands to allow using Colima/K3s as an alternative to Kind. Useful on macOS where a VM is necessary to run Docker anyway. Developing locally in Colima/K3s in the `latest` cluster mode saves time, because the built container images are natively present in the VM, and it is not necessary anymore to load and reload Docker images to the Kind cluster.
> feat(reana-dev): allow using Colima/K3s as an alternative to Kind
