.travis.yml
pytest.ini

docs: more copyright header messages

---

AUTHORS.rst

Signed-off-by: Diego Rodriguez <diego.rodriguez@cern.ch>

docs: amend author name

---

docs/usage.rst

* (addresses #4)
Signed-off-by: Diego Rodriguez <diego.rodriguez@cern.ch>

docs: update installation instructions

---

README.rst
docs/conf.py

docs: addition of Travis/Coveralls/Waffle/Travis/License badges

---

docs/conf.py
docs/examples.rst

docs: ROOT and RooFit example

---

docs/components.rst
docs/gettingstarted.rst
scripts/reana

* Fix images version to v0.0.1.
Signed-off-by: Diego Rodriguez <diego.rodriguez@cern.ch>

config: add reana-server as component

---

docs/gettingstarted.rst
scripts/reana

* Removes hardcoded organization string since
reanahub/reana-workflow-engine-yadage/issues/20 is closed.
Signed-off-by: Diego Rodriguez <diego.rodriguez@cern.ch>

scripts: fix reana run command for v0.0.1

---

docs/components.rst

* Adds REANA-Client, REANA-Cluster and REANA-Workflow-Engine-CWL components.

docs: more components

---

CHANGES.rst
reana/version.py

release: v0.1.0

---

reana/version.py

version: post-release bump

---

AUTHORS.rst
CHANGES.rst
reana/version.py

release: v0.2.0

---

AUTHORS.rst
reana/version.py

docs: author ORCID links

---

README.rst

docs: fix Twitter link

---

docs/conf.py

docs: airy panel

---

reana/cli.py
tests/test_cli.py

* Adds two new convenient helper commands to install (and upgrade) latest REANA
client and cluster scripts.

cli: new install-client and install-cluster commands

---

docs/administratorguide.rst
reana/cli.py

cli: addition of reana-db component

---

AUTHORS.rst
CHANGES.rst
README.rst
docs/administratorguide.rst
docs/gettingstarted.rst
docs/userguide.rst
reana/version.py

* Enriches user guide to explain how one would go about making a research data
analysis reproducible and runnable on REANA cloud.  (closes #85)

docs: richer user guide

---

AUTHORS.rst
docs/administratorguide.rst
docs/gettingstarted.rst

* (closes #88)
Signed-off-by: Jan Okraska <jan.okraska@cern.ch>

docs: add prerequisites link for minikube

---

reana/cli.py
setup.py

* Renames ``reana`` developer helper script to ``reana-dev`` in order to better
express its developer-oriented focus and audience.

cli: reana-dev

---

reana/cli.py
reana/version.py

cli: better code/data/inputs uploading for run-example

---

reana/cli.py

* closes #99
* simplifies environment setup by setting up REANA_ACCESS_TOKEN

cli: simplified setup-environment

---

AUTHORS.rst
CHANGES.rst
docs/administratorguide.rst
docs/gettingstarted.rst
docs/userguide.rst
reana/cli.py
reana/version.py

release: v0.4.0

---

AUTHORS.rst

docs: new contributor

---

reana/cli.py

* Allows to pass input parameters for run-example command.
Closes #121

cli: allow parameters for run-example

---

docs/administratorguide.rst
docs/gettingstarted.rst
reana/cli.py

* Upgrading kubernetes version to 1.12.0.
Connects reanahub/reana-cluster/issues/140

docs: upgrading kubernetes version

---

reana/cli.py

cli: more aggressive git-clean

---

docs/gettingstarted.rst
docs/userguide.rst
reana/cli.py

cli: list became ls

---

reana/cli.py

* Makes it easier to perform integration tests for multiple pull requests
touching also shared components (r-commons, r-db).  (closes #132)

cli: easier shared-module building

---

docs/userguide.rst

* Adds brief instructions on how to declare CVMFS resources.
* Updates section on using existing environments.

docs: CVMFS usage instructions

---

Makefile
docs/administratorguide.rst
docs/gettingstarted.rst

* Upgrades Minikube and Kubectl versions. (connects reanahub/reana-cluster#161)

docs: minikube/0.35 kubectl/1.13.4

---

docs/developerguide.rst

* Provides one line command to open REANA debugging session
(closes reanahub/reana-cluster#173).

docs: amend wdb URL retrieval process

---

docs/administratorguide.rst
docs/gettingstarted.rst
docs/userguide.rst
reana/cli.py

global: kubectl/minikube version upgrade

---

reana/cli.py

* Remove unused argument from git_push command (Closes #152)
* Clarify the description of git_upgrade so it mentions pushing step
Signed-off-by: Jan Okraska <jan.okraska@cern.ch>

cli: fix git_push command

---

Makefile

* Updates installation procedures regarding helm and traefik. (closes #146)

make: helm/traefik updates

---

Makefile

* Connects reanahub/reana-cluster/issues/182

Makefile: minikube/kubectl version upgrade

---

docs/userguide.rst

docs: mention interactive session in user guide

---

CHANGES.rst
README.rst
docs/userguide.rst
reana/version.py

relase: v0.5.0

---

Makefile
reana/cli.py

* Makes ``ci`` user experience smoother and faster by (i) introducing a new
``prefetch`` target to pull interesting images; (ii) polling for cluster setup
and teardown status instead of using fixed sleeping period; (iii) polling for
running demo example termination status instead of using fixed sleeping
period.
* Enriches documentation e.g. for DEMO variable explaining how to run one or
several REANA demo examples.

make: smoother CI user experience

---

reana/cli.py

cli: modifications related to RJC as sidecar

---

Makefile

make: use bash shell

---

setup.py

* Test requirements defined centraly in pytest-reana.

installation: pytest-reana for test requirements

---

reana/cli.py

* Displays whether currently checked-out branch is AHEAD or BEHIND
origin/my-pull-request, origin/master, upstream/pr/NNN, upstream/master.
Useful after running ``reana-dev git-fetch`` for example.
* Amends ``git-branch`` command to show more verbose information.

cli: richer git-status information

---

AUTHORS.rst
docs/developerguide.rst

Signed-off-by: Leticia Farias Wanderley <leticia.farias.wanderley@cern.ch>

docs: add port forwarding info to dev guide

---

Makefile
docs/administratorguide.rst
docs/gettingstarted.rst
reana/cli.py

* Changes ``--generate-default-secrets`` to ``--generate-db-secrets``
when invoking or mentioning ``reana-cluster init``.
(addresses reanahub/reana-cluster#209)

cli: generate-db-secrets

---

Makefile

make: nicer help

---

reana/cli.py

* Report also if my local feature branch stems from an older master.
Useful after running ``reana-dev git-upgrade``.

cli: git-status ahead/behind enhancements

---

docs/userguide.rst
reana/cli.py

cli: new reana-demo-alice-pt-analysis example

---

docs/userguide.rst
reana/cli.py

cli: new reana-demo-cms-reco example

---

Makefile
reana/cli.py

* make: consistent time reporting and colouring
Reports time and uses colours consistently for both ``make`` commands
and ``reana-dev`` commands.
Signed-off-by: Tibor Šimko <tibor.simko@cern.ch>   
* make: tiny sleep to make CI pass

make: consistent time reporting and colouring

---

AUTHORS.rst
Makefile

Signed-off-by: Daniel Prelipcean <daniel.prelipcean@cern.ch>

Updated docs/help in the Makefile

---

Makefile

make: larger sleep for make ci to pass

---

Makefile

* Add additional pip-check to make sure people won't have dependency
conflicts after running make.

makefile: create RS egg-info generated when DEBUG

---

reana/cli.py
reana/version.py

* All components where getting the git describe --dirty tag of the
first component.

cli: fix auto tagging

---

Makefile
reana/cli.py

closes reanahub/reana-cluster#231

make: make virtualbox the default minikube driver

---

reana/cli.py

cli: new CDCI INTEGRAL examples

---

docs/userguide.rst

docs: krb5 fix

---

Makefile

* User creation msg is hidden from server logs.
Addresses reanahub/reana-server/issues/140

Makefile: changes cluster ready check's message

---

Makefile
docs/administratorguide.rst
docs/gettingstarted.rst
reana/cli.py

* Autogenerate secrets will now generate all needed secrets. Secrets
such as CERN SSO and GitLab integration ones
(reanahub/reana-cluster#242).

makefile: use autogenerate secrets

---

docs/userguide.rst

* Addresses reanahub/reana-job-controller/issues/71

docs: adds documentation for comupute backends

---

reana/cli.py

cli: addition of docs.reana.io

---

AUTHORS.rst
CHANGES.rst
reana/version.py
setup.py

release: v0.6.0

---

helm/reana/templates/ingress.yaml
helm/reana/values.yaml

helm: add ssl-redirect annotation

---

Makefile
reana/cli.py

* This is needed for code mounted in the REANA cluster to work
(scenario when running REANA in dev mode).

cli: command to create eggs in all python comp

---

reana/cli.py

cli: fix logging and traceback imports

---

helm/reana/Chart.yaml
helm/reana/templates/cephfs.yaml
helm/reana/templates/reana-message-broker.yaml
helm/reana/templates/reana-server.yaml
helm/reana/templates/reana-ui.yaml
helm/reana/templates/reana-workflow-controller.yaml
helm/reana/values.yaml
reana/cli.py

helm: unify image and tag and add traefik flag

---

helm/reana/templates/roles.yaml
setup.py

* Addresses reanahub/reana-job-controller/issues/3

helm: adds watch permission for core kubernetes api client

---

Makefile
reana/cli.py
tests/test_cli.py

make: add option to exclude components from build

---

reana/cli.py

cli: adapt to new UserToken table

---

index.html
index.js
main.css

docs: index.html to be updated with new releases

---

.github/workflows/helm-releaser.yaml

gh-actions: revert trigger release on push tag

---

CHANGES.rst
docs/administratorguide.rst
docs/gettingstarted.rst
reana/version.py
setup.py

release: v0.6.1

---

CHANGES.rst
helm/reana/templates/ingress.yaml

closes reanahub/reana-server#256

helm: stop exposing invenio-accounts jinja views

---

helm/reana/README.md
helm/reana/templates/announcement-config.yaml
helm/reana/templates/reana-server.yaml
helm/reana/templates/ui-config.yaml
helm/reana/values.yaml

helm: add reana-ui config env vars

---

Makefile

* Addresses reanahub/reana-auth-krb5#1.

make: krb5 image already built by reana-dev

---

CHANGES.rst
reana/cli.py
setup.py
tests/test_cli.py

cli: adapt unit tests to Postgres db container

---

reana/cli.py

cli: support for several cluster modes

---

helm/configurations/values-dev.yaml
helm/reana/templates/cronjobs.yaml
reana/cli.py

helm: limit system status report job history

---

MANIFEST.in
docs/requirements.txt

* Addresses https://github.com/reanahub/reana/issues/335#issuecomment-671231805.

docs: revert deletion of docs/requirements.txt

---

reana/reana_dev/git.py

cli: add git-merge command

---

reana/config.py
reana/reana_dev/git.py
reana/reana_dev/utils.py
setup.py

cli: add git-create-release-commit

---

reana/reana_dev/git.py

cli: git-create-pr

---

reana/reana_dev/cli.py
reana/reana_dev/git.py
reana/reana_dev/release.py

cli: release-pypi

---

reana/reana_dev/git.py

cli: git-tag

---

reana/reana_dev/docker.py
reana/reana_dev/release.py
reana/reana_dev/utils.py

cli: release-docker

---

helm/reana/templates/ui-config.yaml

* See https://github.com/helm/helm/issues/3308.

helm: default values don't work with booleans

---

Makefile
helm/reana/templates/NOTES.txt
reana/reana_dev/cluster.py
reana/reana_dev/run.py
scripts/create-admin-user.sh

closes reanahub/reana-server#270

cli: allow passing email & pwd to cluster-deploy

---

.travis.yml
Makefile
reana/reana_dev/cli.py
reana/reana_dev/run.py
run-tests.sh
scripts/create-admin-user.sh

partially addresses #304
closes #393
closes #394
closes #395

global: multiple minor fixes

---

AUTHORS.rst
reana/reana_dev/cluster.py

Closes: https://github.com/reanahub/reana/issues/387

cli: cluster delete mount option 

---

reana/config.py
reana/reana_dev/cluster.py
reana/reana_dev/run.py
reana/reana_dev/utils.py
tests/test_cli.py

closes https://github.com/reanahub/reana/issues/396

cli: introduce sanity check for `--mode` #396

---

helm/reana/values.yaml

closes https://github.com/reanahub/reana-ui/issues/119

helm: added forum_url to ui-config

---

helm/reana/README.md
helm/reana/templates/NOTES.txt
helm/reana/templates/cronjobs.yaml
helm/reana/templates/ingress.yaml
helm/reana/templates/reana-server.yaml
helm/reana/templates/reana-workflow-controller.yaml
helm/reana/values.yaml
scripts/create-admin-user.sh

scripts: simpler post-installation instructions

---

reana/reana_dev/cluster.py

cli: cluster-deploy not updating submodules/eggs

---

helm/reana/README.md
helm/reana/templates/cronjobs.yaml
helm/reana/values.yaml

closes reanahub/reana-workflow-controller#333

helm: add cronjob to update disk quota nightly

---

helm/reana/README.md
helm/reana/templates/reana-server.yaml
helm/reana/templates/reana-workflow-controller.yaml

helm: add variables to set quota limits

---

.flake8
.github/workflows/ci.yml
MANIFEST.in
run-tests.sh
setup.py
tests/benchmark/locustfile.py

addresses https://github.com/reanahub/reana/issues/456

ci: added flake8 linter

---

tests/benchmark/locustfile.py

* More at https://docs.locust.io/en/latest/changelog.html#changelog-1-0

tests: upgrade code to support locust 1.0+

---

helm/reana/README.md
helm/reana/templates/ui-config.yaml

helm: control ui signup form visibility with configs

---

helm/reana/README.md
helm/reana/templates/ui-config.yaml

addresses https://github.com/reanahub/reana-ui/issues/172

helm: display privacy policy page in UI with cern_ropo flag

---

helm/reana/templates/cronjobs.yaml
helm/reana/templates/reana-server.yaml
helm/reana/templates/roles.yaml

closes #501
closes https://github.com/reanahub/reana-ui/issues/183

helm: grant metrics API permission to cluster role

---

helm/reana/Chart.yaml
helm/reana/values.yaml
reana/version.py
scripts/prefetch-images.sh

release: 0.8.0-alpha.2

---

helm/reana/templates/reana-server.yaml
helm/reana/templates/reana-workflow-controller.yaml
reana/reana_dev/cluster.py

Goes on top of #527
Closes reanahub/reana-workflow-engine-yadage#199

helm: mount new local workspace directories for reana-server

---

reana/config.py

Updates reana-demo-worldpopulation demo image to
reanahub/reana-env-jupyter:2.0.0, following the recent upgrade of the
example.

config: r-d-worldpopulation demo image update

---

reana/reana_dev/python.py

Closes #529
`-k` or `--keep-virtual-environment` flag can be used with `python-unit-tests` from this PR.
Behavior:
- if steps fail, without `-k`, env is not deleted (as before this PR)
- if steps fail, with `-k`, env is not deleted
- If steps succeed, with `-k`, env will not be deleted
- if steps succeed, without `-k`, env will be deleted
- If you rerun the same command with `-k` twice, it will reuse the previously created environment. Is it okay?

Add keep-virtual-environment flag to python-unit-tests command 

---

AUTHORS.rst
reana/reana_dev/helm.py
tests/test_helm.py

cli: helm_upgrade_components, updates Docker images for prefetch script

---

scripts/reana_bench.py

addresses #573
**Important!** in this PR, there is no *range protection*. Meaning you should not cross/mix ranges, etc as it will introduce some strange bugs. This is not a big problem for now but we may want to address it later.

benchmark: add workflow ranges to submit, start and launch commands

---

scripts/reana_bench.py

- removes "submit_number" column from started_results as it is not used;
- renames "submit_date" column to "asked_to_start_date" in started_results for clarity;
- adds new column "collected_date" to collected_results which has a value of datetime when "collect" command was run;
- plots runtime and pending lines in execution_progress even if "started" or "ended" datetimes are missing from collected_results, "collected_date" is used instead;
- do not save analyzed_results to CSV file in "analyze" command as it is not required for anything right now.
closes #573
How to test:
1. Because this PR will bring breaking changes, it will not be possible to analyze results from previous benchmarks out-of-box so the easiest way to test is to run a new short benchmark
2. `submit` some workflows and …

benchmark: allow to plot execution progress from partial results

---

reana/reana_benchmark/analyze.py

- do not substitute missing datetimes with collected datetime, use only the existing one to provide the most accurate results;
- use only finished workflows for total_time and runtime histograms.
closes #598
How to test:
1. You can use this CSV content and save it under `histogram_collected_results.csv`:
```csv
histogram-3,1,2021-11-16T10:24:12,2021-11-16T10:24:39,,running,2021-11-16T10:24:23,2021-11-16T10:24:47
histogram-2,1,2021-11-16T10:24:11,2021-11-16T10:24:37,2021-11-16T10:24:44,finished,2021-11-16T10:24:23,2021-11-16T10:24:47
histogram-5,1,2021-11-16T10:24:11,2021-11-16T10:24:37,2021-11-16T10:24:44,finished,2021-11-16T10:24:23,2021-11-16T10:24:47 …
```

benchmark: use only existing datetimes for histograms

---

LICENSE
helm/reana/Chart.yaml
helm/reana/values.yaml
scripts/prefetch-images.sh

Here is how to test the full PR set:
```
$ reana-dev git-checkout -c CLUSTER -c CLIENT -c reana master
$ reana-dev git-upgrade -c CLUSTER -c CLIENT -c reana master
$ reana-dev git-checkout-pr \
-b r-client 593 \
-b r-j-controller 355 \
-b r-m-broker 46 \
-b r-server 446 \
-b r-ui 226 \
-b r-w-e-cwl 220 \
-b r-w-e-serial 161 \
-b r-w-e-snakemake 37 \
-b r-w-e-yadage 224 \
-b reana 617
$ reana-dev run-ci \
-m /var/reana:/var/reana \
--exclude-components=r-a-krb5,r-a-vomsproxy \
-c r-d-helloworld \
--admin-email john.doe@example.org \
--admin-password mysecretpassword
```

release: 0.9.0-alpha.1

---

reana/reana_benchmark/submit.py

closes https://github.com/reanahub/reana-server/issues/442

benchmark: refactor reana spec loading imports

---

reana/reana_dev/release.py

closes https://github.com/reanahub/reana/issues/627
Issue was caused by the `commit` flag while executing `cr upload`. It is only needed for `maint` branches. This PR introduces an additional `--maint` option to conditionally add this flag.
To test:
1. Create a new release commit (`reana-dev git-create-release-commit -c .`)
2. Create a new tag (`reana-dev git-tag -c .`)
3. `reana-dev release-helm --dry-run` should display:
```
...
cr upload -o reanahub -r reana --release-name-template '{{ .Version }}'
...
```
4. `reana-dev release-helm --dry-run --maint` should display:
```
...
cr upload -o reanahub -r reana --release-name-template '{{ .Version }}' --commit b9f51e4
...
```
5. Remove tag (`git tag -d 0.9.0-alpha.5`)
6. Remove release commit (`git reset --hard HEAD~1`)

cli: add target commit to `release-helm` only for maint branches

---

reana/config.py

- because some new workflows take longer to finish, increase the maximum timeout to wait for workflow results to 15 minutes.
closes #633

config: add new DEMO examples

---

reana/reana_dev/run.py

closes #489
How to test:
1. Try to run a simple `reana-dev run-example -c DEMO` or `-c reana-demo-*` (a single workflow). It should wait until all workflows are finished *sequentially*, and give a summary at the end.
2. Tru to run `--check-only`, it will check workflows sequentially and generate a report.

run: add snapshot for run-example

---

reana/reana_dev/utils.py

cli: sort the list of user-selected components

---

helm/reana/templates/reana-server.yaml

closes reanahub/reana-client#622

helm: add Kubernetes job timeouts to reana-server template

---

CHANGES.rst
helm/reana/templates/reana-db.yaml
reana/config.py
reana/reana_dev/python.py
scripts/prefetch-images.sh

db: move to PostgreSQL 12.10

---

reana/config.py
reana/reana_dev/cli.py
reana/reana_dev/run.py
reana/reana_dev/wiki.py

Closes reanahub/reana-auth-rucio#1.

config: addition of reana-auth-rucio repository

---

CHANGES.rst
helm/reana/templates/reana-db.yaml
reana/config.py
reana/reana_dev/python.py
scripts/prefetch-images.sh

db: move to PostgreSQL 12.13

---

docs/requirements.txt
reana/reana_dev/cluster.py
reana/reana_dev/docker.py
reana/reana_dev/run.py
reana/reana_dev/utils.py

reana-dev: build docker images in parallel

---

CHANGES.rst
reana/reana_dev/client.py
reana/reana_dev/cluster.py

reana-dev: fix deploy/undeploy with custom instance name/namespace

---

.readthedocs.yaml
MANIFEST.in
docs/requirements.txt

docs: add .readthedocs.yaml to migrate to RTD v2

---

helm/reana/README.md
helm/reana/templates/cronjobs.yaml
helm/reana/templates/reana-server.yaml

Closes #736.
Closes reanahub/reana-server#618.

helm: add r-server env variable for enabled notifications

---

helm/reana/Chart.yaml
helm/reana/values.yaml
reana/reana_dev/git.py
reana/version.py
scripts/prefetch-images.sh

- reana-dev: show component name in git-tag
- release: 0.9.1-alpha.4

release: 0.9.1-alpha.4

---

CHANGES.rst
helm/reana/templates/cvmfs.yaml

Closes reanahub/reana-commons#423

helm: add CVMFS storage class

---

.commitlintrc.yaml
helm/reana/Chart.yaml
run-tests.sh

- chore(master): merge maint-0.9 (#803)
- ci(commitlint): improve checking of merge commits (#803)
- build(helm): add support for Kubernetes 1.30 (#799)

chore(master): merge maint-0.9

---

helm/reana/templates/reana-server.yaml

Closes reanahub/reana-workflow-controller#569

feat(helm): add interactive-sessions-env value to reana-server
